# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "addresses", :force => true do |t|
    t.column "name", :string
    t.column "street_address", :string
    t.column "city", :string
    t.column "state", :string
    t.column "zip", :string
  end

end
